// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcFmtqvF5zF6eVYnlMIAclgp7vO-GQ1S4',
    appId: '1:74379867334:android:4eb67f5083499b172193c7',
    messagingSenderId: '74379867334',
    projectId: 'socbay-9e758',
    storageBucket: 'socbay-9e758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9i9-7wHC6iCRnhUjavEu93P0JQpEDMYc',
    appId: '1:74379867334:ios:9052834f80a0011b2193c7',
    messagingSenderId: '74379867334',
    projectId: 'socbay-9e758',
    storageBucket: 'socbay-9e758.firebasestorage.app',
    iosBundleId: 'com.example.socbay',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi2l2Ckp0GNwU6Zp357sxi9JfYRAuxDf8',
    appId: '1:74379867334:web:e31633cd217d12d92193c7',
    messagingSenderId: '74379867334',
    projectId: 'socbay-9e758',
    authDomain: 'socbay-9e758.firebaseapp.com',
    storageBucket: 'socbay-9e758.firebasestorage.app',
    measurementId: 'G-5YTPKBHB5N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9i9-7wHC6iCRnhUjavEu93P0JQpEDMYc',
    appId: '1:74379867334:ios:9052834f80a0011b2193c7',
    messagingSenderId: '74379867334',
    projectId: 'socbay-9e758',
    storageBucket: 'socbay-9e758.firebasestorage.app',
    iosBundleId: 'com.example.socbay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSw1q-s0dSw-79W6HoWjOTXU8zqsQ63Gc',
    appId: '1:74379867334:web:a6091cf49eeaf35f2193c7',
    messagingSenderId: '74379867334',
    projectId: 'socbay-9e758',
    authDomain: 'socbay-9e758.firebaseapp.com',
    storageBucket: 'socbay-9e758.firebasestorage.app',
    measurementId: 'G-94SV6C02ED',
  );
}
